# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    strategy:
      matrix:
        version: [ lucee@6, lucee@5, lucee@4.5, adobe@2023, adobe@2021, adobe@2018, adobe@2016, adobe@11, adobe@10, boxlang@be ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install the ortus security key
      run: apt-key adv --keyserver keys.gnupg.net --recv 6DA70622

    - name: Add the commandbox source
      run: sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list

    - name: Update apt and install commandbox
      run: sudo apt-get update && sudo apt-get --assume-yes install commandbox

    - name: Install dependencies
      run: box install

    - name: Start the ${{ matrix.engine }} CFML engine
      run: box server start cfengine=${{ matrix.engine }} port=8500 openbrowser=false
    
    - name: Run test
      run: box testbox run reporter=mintext > ${{ matrix.engine }}_output.log
    
    - name: Upload output file
      uses: actions/upload-artifact@v4
      with:
        name: output-log-file
        path: ${{ matrix.engine }}_output.log
