name: fw1 Java 11

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    strategy:
      matrix:
        engine: [ lucee@5, adobe@2023, adobe@2021, adobe@2018, adobe@2016 ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install the ortus security key
      run: curl -fsSl https://downloads.ortussolutions.com/debs/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/ortussolutions.gpg > /dev/null

    - name: Add the commandbox source
      run: echo "deb [signed-by=/usr/share/keyrings/ortussolutions.gpg] https://downloads.ortussolutions.com/debs/noarch /" | sudo tee /etc/apt/sources.list.d/commandbox.list

    - name: Update apt and install commandbox
      run: sudo apt-get update && sudo apt-get install apt-transport-https commandbox

    - name: Install dependencies
      run: box install

    - name: Start the ${{ matrix.engine }} CFML engine
      run: box server start cfengine=${{ matrix.engine }} port=8500 openbrowser=false
    
    - name: Run test
      run: box testbox run reporter=mintext
